// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ozonmp/ssn_service_facade/v1/ssn_service_facade.proto

package ssn_service_facade

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Service with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Service) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	return nil
}

// ServiceValidationError is the validation error returned by Service.Validate
// if the designated constraints aren't met.
type ServiceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceValidationError) ErrorName() string { return "ServiceValidationError" }

// Error satisfies the builtin error interface
func (e ServiceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sService.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceValidationError{}

// Validate checks the field values on DescribeServiceV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeServiceV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetServiceId() <= 0 {
		return DescribeServiceV1RequestValidationError{
			field:  "ServiceId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// DescribeServiceV1RequestValidationError is the validation error returned by
// DescribeServiceV1Request.Validate if the designated constraints aren't met.
type DescribeServiceV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeServiceV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeServiceV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeServiceV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeServiceV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeServiceV1RequestValidationError) ErrorName() string {
	return "DescribeServiceV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeServiceV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeServiceV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeServiceV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeServiceV1RequestValidationError{}

// Validate checks the field values on DescribeServiceV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeServiceV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetService()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribeServiceV1ResponseValidationError{
				field:  "Service",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// DescribeServiceV1ResponseValidationError is the validation error returned by
// DescribeServiceV1Response.Validate if the designated constraints aren't met.
type DescribeServiceV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeServiceV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeServiceV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeServiceV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeServiceV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeServiceV1ResponseValidationError) ErrorName() string {
	return "DescribeServiceV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeServiceV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeServiceV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeServiceV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeServiceV1ResponseValidationError{}

// Validate checks the field values on ListServicesV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListServicesV1Request) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Offset

	if val := m.GetLimit(); val <= 0 || val > 500 {
		return ListServicesV1RequestValidationError{
			field:  "Limit",
			reason: "value must be inside range (0, 500]",
		}
	}

	return nil
}

// ListServicesV1RequestValidationError is the validation error returned by
// ListServicesV1Request.Validate if the designated constraints aren't met.
type ListServicesV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListServicesV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListServicesV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListServicesV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListServicesV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListServicesV1RequestValidationError) ErrorName() string {
	return "ListServicesV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListServicesV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListServicesV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListServicesV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListServicesV1RequestValidationError{}

// Validate checks the field values on ListServicesV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListServicesV1Response) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetServices() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListServicesV1ResponseValidationError{
					field:  fmt.Sprintf("Services[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for IsHasPrevPage

	// no validation rules for IsHasNextPage

	return nil
}

// ListServicesV1ResponseValidationError is the validation error returned by
// ListServicesV1Response.Validate if the designated constraints aren't met.
type ListServicesV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListServicesV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListServicesV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListServicesV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListServicesV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListServicesV1ResponseValidationError) ErrorName() string {
	return "ListServicesV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListServicesV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListServicesV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListServicesV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListServicesV1ResponseValidationError{}
