global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'ssn-service-api'
    static_configs:
      - targets:
        - ssn-service-api:9100
  - job_name: 'ssn-service-api-events-retranslator'
    static_configs:
      - targets:
        - ssn-service-api-events-retranslator:9100
  - job_name: 'ssn-service-facade'
    static_configs:
      - targets:
        - ssn-service-facade:9100
  - job_name: 'ssn-service-facade-grpc'
    static_configs:
      - targets:
        - ssn-service-facade-grpc:9100
  - job_name: 'ssn-service-bot'
    static_configs:
      - targets:
        - ssn-service-bot:9100
