global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'ssn-service-api'
    static_configs:
      - targets:
        - ssn-service-api:9100
  - job_name: 'ssn-service-api-events-retranslator'
    static_configs:
      - targets:
        - ssn-service-api-events-retranslator:9101
