# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: ozonmp/ssn_service_api/v1/ssn_service_api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import validate.validate_pb2
import google.api.annotations_pb2
import google.protobuf.timestamp_pb2
import ozonmp.ssn_service_api.v1.ssn_service_api_pb2


class SsnServiceApiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def CreateServiceV1(self, stream: 'grpclib.server.Stream[ozonmp.ssn_service_api.v1.ssn_service_api_pb2.CreateServiceV1Request, ozonmp.ssn_service_api.v1.ssn_service_api_pb2.CreateServiceV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def DescribeServiceV1(self, stream: 'grpclib.server.Stream[ozonmp.ssn_service_api.v1.ssn_service_api_pb2.DescribeServiceV1Request, ozonmp.ssn_service_api.v1.ssn_service_api_pb2.DescribeServiceV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def UpdateServiceV1(self, stream: 'grpclib.server.Stream[ozonmp.ssn_service_api.v1.ssn_service_api_pb2.UpdateServiceV1Request, ozonmp.ssn_service_api.v1.ssn_service_api_pb2.UpdateServiceV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def ListServicesV1(self, stream: 'grpclib.server.Stream[ozonmp.ssn_service_api.v1.ssn_service_api_pb2.ListServicesV1Request, ozonmp.ssn_service_api.v1.ssn_service_api_pb2.ListServicesV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def RemoveServiceV1(self, stream: 'grpclib.server.Stream[ozonmp.ssn_service_api.v1.ssn_service_api_pb2.RemoveServiceV1Request, ozonmp.ssn_service_api.v1.ssn_service_api_pb2.RemoveServiceV1Response]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ozonmp.ssn_service_api.v1.SsnServiceApiService/CreateServiceV1': grpclib.const.Handler(
                self.CreateServiceV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.ssn_service_api.v1.ssn_service_api_pb2.CreateServiceV1Request,
                ozonmp.ssn_service_api.v1.ssn_service_api_pb2.CreateServiceV1Response,
            ),
            '/ozonmp.ssn_service_api.v1.SsnServiceApiService/DescribeServiceV1': grpclib.const.Handler(
                self.DescribeServiceV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.ssn_service_api.v1.ssn_service_api_pb2.DescribeServiceV1Request,
                ozonmp.ssn_service_api.v1.ssn_service_api_pb2.DescribeServiceV1Response,
            ),
            '/ozonmp.ssn_service_api.v1.SsnServiceApiService/UpdateServiceV1': grpclib.const.Handler(
                self.UpdateServiceV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.ssn_service_api.v1.ssn_service_api_pb2.UpdateServiceV1Request,
                ozonmp.ssn_service_api.v1.ssn_service_api_pb2.UpdateServiceV1Response,
            ),
            '/ozonmp.ssn_service_api.v1.SsnServiceApiService/ListServicesV1': grpclib.const.Handler(
                self.ListServicesV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.ssn_service_api.v1.ssn_service_api_pb2.ListServicesV1Request,
                ozonmp.ssn_service_api.v1.ssn_service_api_pb2.ListServicesV1Response,
            ),
            '/ozonmp.ssn_service_api.v1.SsnServiceApiService/RemoveServiceV1': grpclib.const.Handler(
                self.RemoveServiceV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.ssn_service_api.v1.ssn_service_api_pb2.RemoveServiceV1Request,
                ozonmp.ssn_service_api.v1.ssn_service_api_pb2.RemoveServiceV1Response,
            ),
        }


class SsnServiceApiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateServiceV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.ssn_service_api.v1.SsnServiceApiService/CreateServiceV1',
            ozonmp.ssn_service_api.v1.ssn_service_api_pb2.CreateServiceV1Request,
            ozonmp.ssn_service_api.v1.ssn_service_api_pb2.CreateServiceV1Response,
        )
        self.DescribeServiceV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.ssn_service_api.v1.SsnServiceApiService/DescribeServiceV1',
            ozonmp.ssn_service_api.v1.ssn_service_api_pb2.DescribeServiceV1Request,
            ozonmp.ssn_service_api.v1.ssn_service_api_pb2.DescribeServiceV1Response,
        )
        self.UpdateServiceV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.ssn_service_api.v1.SsnServiceApiService/UpdateServiceV1',
            ozonmp.ssn_service_api.v1.ssn_service_api_pb2.UpdateServiceV1Request,
            ozonmp.ssn_service_api.v1.ssn_service_api_pb2.UpdateServiceV1Response,
        )
        self.ListServicesV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.ssn_service_api.v1.SsnServiceApiService/ListServicesV1',
            ozonmp.ssn_service_api.v1.ssn_service_api_pb2.ListServicesV1Request,
            ozonmp.ssn_service_api.v1.ssn_service_api_pb2.ListServicesV1Response,
        )
        self.RemoveServiceV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.ssn_service_api.v1.SsnServiceApiService/RemoveServiceV1',
            ozonmp.ssn_service_api.v1.ssn_service_api_pb2.RemoveServiceV1Request,
            ozonmp.ssn_service_api.v1.ssn_service_api_pb2.RemoveServiceV1Response,
        )
