# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ozonmp/ssn_service_api/v1/ssn_service_event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ozonmp/ssn_service_api/v1/ssn_service_event.proto',
  package='ozonmp.ssn_service_api.v1',
  syntax='proto3',
  serialized_options=_b('ZEgithub.com/ozonmp/ssn-service-api/pkg/ssn-service-api;ssn_service_api'),
  serialized_pb=_b('\n1ozonmp/ssn_service_api/v1/ssn_service_event.proto\x12\x19ozonmp.ssn_service_api.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x01\n\x13ServiceEventPayload\x12(\n\nservice_id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00H\x00R\tserviceId\x12\x1f\n\x04name\x18\x02 \x01(\tB\t\xfa\x42\x06r\x04\x10\x01\x18\x64H\x01R\x04name\x12.\n\x0b\x64\x65scription\x18\x03 \x01(\tB\n\xfa\x42\x07r\x05\x10\x01\x18\xc8\x01H\x02R\x0b\x64\x65scriptionB\r\n\x0b_service_idB\x07\n\x05_nameB\x0e\n\x0c_descriptionBGZEgithub.com/ozonmp/ssn-service-api/pkg/ssn-service-api;ssn_service_apib\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SERVICEEVENTPAYLOAD = _descriptor.Descriptor(
  name='ServiceEventPayload',
  full_name='ozonmp.ssn_service_api.v1.ServiceEventPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_id', full_name='ozonmp.ssn_service_api.v1.ServiceEventPayload.service_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\0042\002 \000'), json_name='serviceId', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ozonmp.ssn_service_api.v1.ServiceEventPayload.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\006r\004\020\001\030d'), json_name='name', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='ozonmp.ssn_service_api.v1.ServiceEventPayload.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\372B\007r\005\020\001\030\310\001'), json_name='description', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_service_id', full_name='ozonmp.ssn_service_api.v1.ServiceEventPayload._service_id',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='ozonmp.ssn_service_api.v1.ServiceEventPayload._name',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='_description', full_name='ozonmp.ssn_service_api.v1.ServiceEventPayload._description',
      index=2, containing_type=None, fields=[]),
  ],
  serialized_start=169,
  serialized_end=353,
)

_SERVICEEVENTPAYLOAD.oneofs_by_name['_service_id'].fields.append(
  _SERVICEEVENTPAYLOAD.fields_by_name['service_id'])
_SERVICEEVENTPAYLOAD.fields_by_name['service_id'].containing_oneof = _SERVICEEVENTPAYLOAD.oneofs_by_name['_service_id']
_SERVICEEVENTPAYLOAD.oneofs_by_name['_name'].fields.append(
  _SERVICEEVENTPAYLOAD.fields_by_name['name'])
_SERVICEEVENTPAYLOAD.fields_by_name['name'].containing_oneof = _SERVICEEVENTPAYLOAD.oneofs_by_name['_name']
_SERVICEEVENTPAYLOAD.oneofs_by_name['_description'].fields.append(
  _SERVICEEVENTPAYLOAD.fields_by_name['description'])
_SERVICEEVENTPAYLOAD.fields_by_name['description'].containing_oneof = _SERVICEEVENTPAYLOAD.oneofs_by_name['_description']
DESCRIPTOR.message_types_by_name['ServiceEventPayload'] = _SERVICEEVENTPAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceEventPayload = _reflection.GeneratedProtocolMessageType('ServiceEventPayload', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEEVENTPAYLOAD,
  __module__ = 'ozonmp.ssn_service_api.v1.ssn_service_event_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.ssn_service_api.v1.ServiceEventPayload)
  ))
_sym_db.RegisterMessage(ServiceEventPayload)


DESCRIPTOR._options = None
_SERVICEEVENTPAYLOAD.fields_by_name['service_id']._options = None
_SERVICEEVENTPAYLOAD.fields_by_name['name']._options = None
_SERVICEEVENTPAYLOAD.fields_by_name['description']._options = None
# @@protoc_insertion_point(module_scope)
